# Generated by Django 4.2.5 on 2023-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='manga_images'),
        ),
        migrations.AddField(
            model_name='manga',
            name='numberOfChapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='tag',
            field=models.ManyToManyField(related_name='mangas', to='manga.tag'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
