# Generated by Django 4.2.5 on 2023-10-01 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_manga_author_manga_img_manga_numberofchapters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='img',
            new_name='banner',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='tag',
        ),
        migrations.AddField(
            model_name='manga',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='mangas', to='manga.tag'),
        ),
    ]
