# Generated by Django 4.2.5 on 2023-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_rename_img_manga_banner_remove_manga_tag_manga_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='tag',
        ),
        migrations.AddField(
            model_name='manga',
            name='tag',
            field=models.ManyToManyField(default='', related_name='mangas', to='manga.tag'),
        ),
    ]
