# Generated by Django 4.2.5 on 2023-10-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_remove_manga_tag_manga_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='overview',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
