# Generated by Django 4.2.5 on 2023-10-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_manga_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='overview',
            field=models.TextField(default=''),
        ),
    ]
