# Generated by Django 4.2.5 on 2023-10-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_manga_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
