# Generated by Django 4.2.5 on 2023-10-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_alter_manga_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='overview',
        ),
        migrations.AddField(
            model_name='manga',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
