# Generated by Django 4.2.5 on 2023-10-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_remove_manga_overview_manga_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='manga',
            name='overlook',
            field=models.TextField(blank=True, null=True),
        ),
    ]
