# Generated by Django 4.2.5 on 2023-10-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_chapter_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='page',
            name='Chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.ManyToManyField(related_name='Pages', to='manga.page'),
        ),
        migrations.AddField(
            model_name='manga',
            name='chapters',
            field=models.ManyToManyField(related_name='Chapters', to='manga.chapter'),
        ),
    ]
