# Generated by Django 4.2.5 on 2023-10-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_chapters_remove_manga_chapters_delete_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapters',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='manga',
            name='chapterfiles',
            field=models.FileField(default='manga_images', upload_to='manga_images'),
        ),
    ]
