# Generated by Django 4.2.5 on 2023-10-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_remove_chapter_manga_remove_page_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='numberOfPages',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='pages',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.ImageField(blank=True, null=True, upload_to='manga_images'),
        ),
    ]
