# Generated by Django 4.2.5 on 2023-10-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0017_remove_chapter_numberofpages_remove_chapter_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='pages',
            field=models.FileField(blank=True, null=True, upload_to='manga_images'),
        ),
    ]
