# Generated by Django 4.2.5 on 2023-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_author_page_alter_manga_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
