# Generated by Django 4.2.5 on 2023-10-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0020_alter_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
