# Generated by Django 4.2.5 on 2023-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0021_delete_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='pages',
        ),
    ]
