# Generated by Django 4.2.5 on 2023-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingPage', '0002_remove_page_chapter_alter_page_image'),
        ('manga', '0022_remove_chapter_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='page',
            field=models.ManyToManyField(to='readingPage.page'),
        ),
    ]
