# Generated by Django 4.2.5 on 2023-10-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0023_chapter_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='page',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='chapters',
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
    ]
