# Generated by Django 4.2.5 on 2023-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0026_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['updated']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
