# Generated by Django 4.2.5 on 2023-10-05 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga', '0028_alter_chapter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='like',
            field=models.ManyToManyField(related_name='like_manga', to=settings.AUTH_USER_MODEL),
        ),
    ]
