# Generated by Django 4.2.5 on 2023-10-07 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga', '0029_manga_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='manga',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_manga', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manga',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
