# Generated by Django 4.2.5 on 2023-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0030_author_slug_chapter_slug_tag_slug_alter_manga_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='manga_images'),
        ),
    ]
