# Generated by Django 4.2.5 on 2023-10-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0031_manga_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='numberOfChapters',
        ),
    ]
