# Generated by Django 4.2.6 on 2023-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0033_chapter_user_visited_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
