# Generated by Django 4.2.5 on 2023-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
