# Generated by Django 4.2.5 on 2023-10-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0025_rename_chapter_chapter_name_alter_chapter_manga_and_more'),
        ('readingPage', '0002_remove_page_chapter_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='manga.chapter'),
        ),
    ]
