# Generated by Django 4.2.5 on 2023-10-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingPage', '0003_page_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
